services:
  portfolio-boris-app:
    image: us-central1-docker.pkg.dev/nine-tones-bots-2025-468320/tasty-ar/portfolio_boris:latest
    container_name: portfolio-boris-app
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - web
    expose:
      - "80"  # Nginx serves on port 80 inside container
    ports:
      - "8081:80"  # Map to port 8081 on host to avoid conflicts
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.3'
        reservations:
          memory: 256M
          cpus: '0.1'

networks:
  web:
    external: true